name: Main Workflow
on:
  schedule:
    - cron:  '0 * * * *'
  issues:  
    types: [opened, edited]
jobs:
  Ubuntu:
    name: Add labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: alexleventer/github-issue-due-dates-action@1.2.0
        with:
          GH_TOKEN: "${{ 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 }}"
